defaults:
  - data: shapenet
  - model: choir
  - callbacks: default
  - trainer: default
  - paths: default
  - override hydra/job_logging: none
  - _self_

seed: 0
ckpt_path: ???

hydra:
  output_subdir: null
  run:
    dir: .
