defaults:
  - data: shapenet
  - model: choir
  - optim: adam
  - scheduler: cosine
  - callbacks: default
  - logger: wandb
  - trainer: default
  - paths: default
  - experiment: null
  - override hydra/job_logging: none
  - _self_

seed: 0
test_after_training: true

tags:
  - ${hydra:runtime.choices.model}
  - ${hydra:runtime.choices.experiment}

hydra:
  output_subdir: null
  run:
    dir: .
